services:
  - type: web
    name: voice-receptionist
    env: node
    region: oregon 
    buildCommand: npm install && npm run build
    startCommand: npm start
    branch: master
    autoDeploy: true
